### ISSUE TITLE
[Formatter]Could not format code

### ISSUE THREAD

**Issue by michaelst** [Shaked/phpstorm-phpfmt#1]
I get an error that the formatter could not format the code in PhpStorm

**Comment by Shaked** [comment]
@michaelst do you have the .phar? If not, you will have to download it manually and set up the correct path. 

https://github.com/watscho/phpfmt/blob/master/fmt.phar might work. I am sure you can find more copies available. 

Lemme know if it works for you, otherwise, please post more details. 

Shaked

**Comment by michaelst** [comment]
I downloaded fmt.phar and added the path inside settings but I am still getting the same error. I tried a couple variations on the path and still got the same error.
![screen shot 2016-10-26 at 4 23 41 pm](https://cloud.githubusercontent.com/assets/4080508/19747374/98656544-9b98-11e6-8e6c-b22fe4775c9b.png)

**Comment by Shaked** [comment]
Can you please elaborate on the error? 

I see that you are using php5, right? You should use php7 AFAI remember.

**Comment by michaelst** [comment]
That is the path to php7 on my mac. 

Every time the auto format runs I get a message in the event log saying [Formatter]Could not format code. I get the same message when I click format code under Code. I don't know what more details I can provide.

**Comment by Shaked** [comment]
1. Please write down your system information. 
2. Please copy-paste `/usr/local/php5/php -v` 
3. Please use the `Debug` option in the phpstorm options and print the error from the event log.

**Comment by michaelst** [comment]
I got it to work by using the path including php `/usr/local/php5/bin/php`

**Comment by Shaked** [comment]
Great. 

Thank you for letting me know!

Shaked
